### ISSUE TITLE
How to use the trained model?

### ISSUE THREAD

**Issue by CFZ3668** [med-air/DEX#1]
I have followed your steps for training, but how should I get test data and use the trained model for testing? Looking forward to your recovery

**Comment by TaoHuang13** [comment]
Thanks for your question @S3668. 

Actually, we have integrated the evaluation module into the WandB. The evaluation is launched on the environment during training, thus no test data will be used. The evaluation results can be found in both WandB and the local log directory (exp_local/#task_name/#algo_name/#d100/#seed/eval.csv).

You may follow the[ office guidance of WandB](https://docs.wandb.ai/ref/cli/wandb-login) to register your WandB account for result visualization. 

Please let me know if there are any further questions.
