### ISSUE TITLE
wandb problem

### ISSUE THREAD

**Issue by kidd12138** [med-air/DEX#10]
I have created a wandb account and changed the wandb entity in train.yaml before running the command,but it appears the error below.Is there anything else should be modified?

![屏幕截图 2024-07-21 104512](https://github.com/user-attachments/assets/35203fed-d771-40bd-8da8-245c30d2eb6c)

**Comment by TaoHuang13** [comment]
Hi. I guess this is because the configuration parser views your wandb account as an integer (384684286) rather than a string. You should force a type transfer (`str(x)`) before [wandb.init()](https://github.com/med-air/DEX/blob/0307c64ff037d4de85eadf325ac542dfa938b265/dex/components/logger.py#L78).

**Comment by kidd12138** [comment]
Probably.I tried to create another wandb account with no integer and it didn't happen again.Thanks for the advice.And there is another question,I see there are quite a few parameters uploaded on the wandb,what parameters  should be compared to evaluate the effectiveness of  RL methods?I don't know if it's too simple,I'm still in the process of learning it.

**Comment by TaoHuang13** [comment]
Glad to hear that. Regarding evaluating RL, the most direct metric is the evaluated episode reward (task success rate in our tasks). Other metrics, such as critic loss or policy loss, are somehow meaningless. It also depends on the RL algorithm you choose.
