### ISSUE TITLE
Detail parameters in Expert Demonstration Data

### ISSUE THREAD

**Issue by HMcoconut** [med-air/DEX#11]
May I know what are the meaning of each value in the demonstration data?

```python
>>> import numpy as np
>>> data = np.load('data_BiPegTransfer-v0_random_100.npz', allow_pickle=True)
>>> data['obs'][0][0]['observation']
array([ 2.50000024e+00,  2.50000328e-01,  3.77600002e+00, -1.57077582e+00,
       -7.86881280e-06,  1.57089384e+00, -2.68686934e-08,  2.50000024e+00,
       -2.50000358e-01,  3.77600002e+00, -1.57077499e+00,  8.22652205e-06,
        1.57069500e+00,  2.63462330e-08,  2.81499942e+00, -1.35001428e-01,
        3.52300466e+00,  3.14999185e-01, -3.85001756e-01, -2.52995362e-01,
        3.14999185e-01,  1.14998930e-01, -2.52995362e-01,  2.83223295e+00,
       -1.16891325e-01,  3.52300572e+00,  1.95795628e-05,  3.74380987e-05,
       -2.33138680e+00,  2.82206702e+00, -1.58981025e-01,  3.52300453e+00,
       -4.22121162e-05, -1.76266571e-06,  1.85740287e+00])
>>> data['obs'][0][0]['observation'].shape
(35, )
```

The observation's size is 35 for the BiPegTransfer task, what are those values represented?

Thank you in advance!

**Comment by TaoHuang13** [comment]
Please see [here](https://github.com/med-air/SurRoL/blob/b0b7068e825fdb9b6872c92b4428829dece64472/surrol/tasks/psm_env.py#L147).

**Comment by HMcoconut** [comment]
Hello, where can I find the meaning of each action values in the demonstration data?

```python
>>> import numpy as np
>>> data = np.load('data_NeedlePick-v0_random_100.npz', allow_pickle=True)
>>> data['acs'][0][0]
array([ 0.27930372, -0.4       , -0.14245996, -0.4       ,  0.5       ])
```

I have read the **SurRoL: An Open-source Reinforcement Learning Centered and dVRK Compatible Platform for Surgical Robot Learning** paper, and found out that "action space is $(d_x,d_y,d_z,d_{yaw}/d_{pitch},j)$, where $d_x,d_y,d_z$ determine the position movement in the Cartesian space, $d_{yaw}/d_{pitch}$ determines the orientation movement in a top-down or vertical space setting, respectively, and $j$ determines whether the jaw is open $(j ≥0)$ or close $(j < 0)$."

At first I thought 0.27930372 is the change in $x$ direction, -0.4 is the change in $y$ direction, and -0.14245996 is the change in $z$ direction. However, when I tried to subtract values from 2 consecutive observation data, the difference obtained in $x, y, z$ coordinate is not equal to the values in `acs`.

```python
>>> data['obs'][0][1]['observation'] -  data['obs'][0][0]['observation']
array([ 1.38640404e-02, -1.98618323e-02, -7.07554817e-03,  1.75841342e-05,
        7.84772036e-05, -2.07962564e-01,  6.93688287e-01,  7.64262875e-10,
       -1.90799910e-09,  1.69147188e-05, -1.38640396e-02,  1.98618304e-02,
        7.09246289e-03,  0.00000000e+00,  0.00000000e+00,  1.83582306e-05,
       -5.93353128e-09,  2.89223586e-08, -1.07350008e-07])
```

If I understand correctly, the first 3 terms should correspond to the position of robot state. These should equal to the first 3 terms in `acs[0][0]` if the data given is indeed $(d_x,d_y,d_z,d_{yaw}/d_{pitch},j)$.

**Comment by TaoHuang13** [comment]
There is a scaling operation on the action (see [here](https://github.com/med-air/SurRoL/blob/b0b7068e825fdb9b6872c92b4428829dece64472/surrol/tasks/psm_env.py#L189)), where the action will be scaled with 0.01 * 5 in the NeedlePick task ([self.SCALING=5](https://github.com/med-air/SurRoL/blob/b0b7068e825fdb9b6872c92b4428829dece64472/surrol/tasks/needle_pick.py#L17C5-L17C17)).
