### ISSUE TITLE
failed to EGL with glad.

### ISSUE THREAD

**Issue by JauJieYou** [med-air/DEX#2]
Dear Professor
  I had installed as web, and the demo of "python SurRoL/surrol/data/data_generation.py --env NeedlePick-v0" running OK. But it failed for the Training Commands, showing "failed to EGL with glad." Is there necessary for GPU installed? (I have no GPU). Or, is there anything I miss?

**Comment by TaoHuang13** [comment]
Hi Jaujie,

The default device for training is GPU, while you could still try it by setting the device as CPU through the following command:

`python3 train.py task=NeedlePick-v0 agent=dex use_wb=True device=cpu`

Hope it helps.
