### ISSUE TITLE
where is the training data file (.npz)?

### ISSUE THREAD

**Issue by JauJieYou** [med-air/DEX#3]
Dear Sir
  Thanks for previous answering the EGL problem. It is EGL problem, and I finally using a GPU card, to bypass this problem.
  After trying using the `python3 train.py task=NeedlePick-v0 agent=dex use_wb=False`, I could find the .pth files, but I cannot .npz files. Where could I find it, for `python SurRoL/surrol/data/data_generation.py --env NeedlePick-v0` 
  Another question are: 
  It will jump broken after training for few hours, and showed "pybullet.error: Not connected to physics server". And when I try re-do the training, it clean all the previous training .pth files. When the training is broken, how could I re-training?
Thanks a lot.

**Comment by TaoHuang13** [comment]
Hi Jaujie,

You may find the .npz (demo file) in /SurRoL/surrol/data/demo by just following the demo-collection commands, and you don't need to run the training command.

As for the re-training, we suggest you to adjust the training steps to your desired one (100k as default) my modifying the training_steps in configuration file /dex/configs/train.yaml. If you still want to do multi-state training, you may save the replay buffer, optimizers, and neural networks and reload them to the re-training state.

Hope it helps

**Comment by JauJieYou** [comment]
Dear TaoHuang
  Thanks a lot, for your kind reply.
  It sounds like there are no .npz files after training. So how do you record it in the demo?
  And what is your suggestion for training steps setting?

  Besides, may I ask a question about RL basics? What is a good starting method in surgical robot automation?  You cited some other methods, but I have no idea how to learn them. For example, starting with xgboost for data evaluation may be the first step in Kaggle competition. But for surgical robot RL, what is your suggestion?

  After all, your DEX method is a superior result. I am waiting for your new paper of ViSkill. 
Thanks very much.

**Comment by TaoHuang13** [comment]
Hi,

1. Sure, no .npz files after training. It was only used to save demonstrations before training.
2. 100K training steps are recommended for reproduction. But you are also suggested to increase it to obtain better models.
3. For the Chinese version, I recommend https://github.com/wangshusen/DRL, a book by Shusen Wang, for beginners. Then it should be easier for you to follow the related work.
4. Thanks for your kind words. ViSkill is on its way :)
