### ISSUE TITLE
Adjusting x and y Angles

### ISSUE THREAD

**Issue by provuss** [med-air/DEX#8]
Hello,

I find your approach to work impressively well. I am currently trying to extend the needle pick to a starting position where the needle is not lying flat on a surface but is partially inserted into the tissue. For now, this can't work because in training the sampler only generates episodes with rotation around x- and y-axis being zero. If I change this I assume that I also have to change some hyperparameters in train.yaml. Do you have any suggestions on which ones would be necessary to change?

**Comment by TaoHuang13** [comment]
Hi @provuss, this is a good question. If you want to set different poses of the need, I suggest you modify the task class itself to change the setup of this task. The train.yaml file only determines RL setup, which may not be helpful to your intention.

Please take a closer look at [this part](https://github.com/med-air/SurRoL/blob/b0b7068e825fdb9b6872c92b4428829dece64472/surrol/tasks/needle_pick.py#L21).
